### ISSUE TITLE
build fails (on linux at least)

### ISSUE THREAD

**Issue by stronnag** [iNavFlight/inav-configurator#1501]
```
[18:18:50] 'build-js' errored after 47 ms
[18:18:50] Error: File not found with singular glob: /t/configurators/inav-configurator/node_modules/three/build/three.min.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/t/configurators/inav-configurator/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:642:26)
    at Glob.emit (node:events:527:28)
    at Glob.emit (node:domain:475:12)
    at Glob._finish (/t/configurators/inav-configurator/node_modules/glob/glob.js:194:8)
    at done (/t/configurators/inav-configurator/node_modules/glob/glob.js:179:14)
    at Glob._processSimple2 (/t/configurators/inav-configurator/node_modules/glob/glob.js:685:12)
    at /t/configurators/inav-configurator/node_modules/glob/glob.js:673:10
    at Glob._stat2 (/t/configurators/inav-configurator/node_modules/glob/glob.js:769:12)
    at lstatcb_ (/t/configurators/inav-configurator/node_modules/glob/glob.js:761:12)
```

```
$ find . -iname three.min.js 
./node_modules/three/three.min.js
```

**Comment by stronnag** [comment]
As of:

```
$ git log
commit bdc485d4f5a155edbcb081b89870110f29a10945 (HEAD -> master, origin/master, origin/HEAD)
Merge: c0c74916 badd9cea
Author: Paweł Spychalski <pspychalski@gmail.com>
Date:   Tue Apr 5 13:51:37 2022 +0200
```

**Comment by stronnag** [comment]
`nom install`
