### ISSUE TITLE
8 rc3 configuratorthere is no airframe rending.

### ISSUE THREAD

**Issue by and-sh** [iNavFlight/inav-configurator#2286]
After latest update on Debian 13 there is no airframe. On windows all work fine.
![Screenshot From 2024-12-15 17-19-16](https://github.com/user-attachments/assets/6c0f1918-a07d-4fb3-b16d-909662252bd1)
![Screenshot From 2024-12-16 09-23-59](https://github.com/user-attachments/assets/3ea5491c-0e3a-4d01-b9a5-7b54d14586a7)

In alignment tab the same.

I guess this is not very urgent because Debian 13 will be released in about a year.

**Comment by sensei-hacker** [comment]
That would probably be your 3D rendering / GPU drivers and configuration. If you have an Nvidia card with their driver,  you have to compile the proprietary Nvidia driver for each kernel update.

Since you're running a Debian branch that's a year before release, I probably don't need to tell you how to use journalctl to check the logs, etc. :)

**Comment by and-sh** [comment]
![Screenshot From 2024-12-16 14-23-21](https://github.com/user-attachments/assets/05d5c6ce-e314-477e-9754-aceb6df56d15)

**Comment by stronnag** [comment]
This happens on modern Linux systems due to upstream issues in Electron. 
Unlikely that INAV can fix it.
It's happened ever since the configurator Electron migration.

**Comment by and-sh** [comment]
Thank you. Hope they fix that soon.

**Comment by Scavanger** [comment]
Fixed in #2285

**Comment by and-sh** [comment]
Can I test this?
![Screenshot From 2024-12-18 09-14-03](https://github.com/user-attachments/assets/3cb5e290-89a5-4762-a7f4-7451578e7c30)

**Comment by Scavanger** [comment]
> Can I test this? 

Sure, go to the PR -> Checks -> Artifacts and download the installer/archive

**Comment by and-sh** [comment]
Yep, work fine. 
![Screenshot From 2024-12-18 19-31-10](https://github.com/user-attachments/assets/1346e0b7-e656-4c18-b546-bd7b06e5f6fd)

But there are some warnings in console

[198545:1218/193441.898004:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[198545:1218/193453.065980:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
We're closing...
(node:198509) UnhandledPromiseRejectionWarning: TypeError: js.stopAll is not a function
    at App.<anonymous> (file:///usr/lib/inav-configurator/resources/app/.vite/build/main.js:11684:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at emitUnhandledRejectionWarning (node:internal/process/promises:298:15)
    at warnWithErrorCodeUnhandledRejectionsMode (node:internal/process/promises:406:5)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:198509) TypeError: js.stopAll is not a function
    at App.<anonymous> (file:///usr/lib/inav-configurator/resources/app/.vite/build/main.js:11684:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Scavanger** [comment]
> But there are some warnings in console

Still a Bug in electron (chromeium): https://github.com/electron/electron/issues/32760

Seems to work on some systems, on some not.
We have to disable GPU acceleration on Linux to get it work on all systems, but makes the 3D rendings sluggish. :(

**Comment by and-sh** [comment]
Not at all. 
But the propellers are not positioned correctly. All counterclockwise.
In Betaflight too.

**Comment by b14ckyy** [comment]
Since main issue seems to be fixed and further improvements are on the Linux side, will close here.
