### ISSUE TITLE
v2.0 Cannot save tricopter mixer

### ISSUE THREAD

**Issue by rtlopez** [iNavFlight/inav-configurator#542]
master: 594cad7d0b29b7db9de03de710fbeff23b93bb39 

```
12995:13013:0713/222436.200186:ERROR:web_database_backend.cc(113)] Cannot initialize the web database: 2
[12995:12995:0713/222436.223544:ERROR:desktop_window_tree_host_x11.cc(1101)] Not implemented reached in virtual void views::DesktopWindowTreeHostX11::InitModalType(ui::ModalType)
chrome-extension://modhfcbjjfkllpnmlfikolhikailmeno/build/script.js:23262
        googleAnalytics.sendEvent('Mixer', 'Platform type', helper.platform.getList()[MIXER_CONFIG.platformType].name);
                                                                                                                ^
TypeError: Cannot read `property` 'name' of undefined
    at HTMLAnchorElement.saveAndReboot (chrome-extension://modhfcbjjfkllpnmlfikolhikailmeno/build/script.js:23262:113)
    at HTMLAnchorElement.dispatch (chrome-extension://modhfcbjjfkllpnmlfikolhikailmeno/build/script.js:91:6466)
    at HTMLAnchorElement.r.handle (chrome-extension://modhfcbjjfkllpnmlfikolhikailmeno/build/script.js:91:3241)

```
fix probably should be:
```
- googleAnalytics.sendEvent('Mixer', 'Platform type', helper.platform.getList()[MIXER_CONFIG.platformType].name);
+ googleAnalytics.sendEvent('Mixer', 'Platform type', helper.platform.getById(MIXER_CONFIG.platformType).name);
```

Hope, this helps, 
Cheers, Lopez ;)

**Comment by rtlopez** [comment]
Oops, I checked wrong branch, it's already fixed, Cheers ;)
